on:
  workflow_dispatch:
    inputs:
      annotation:
        description: 'Comments'

name: Release latest QSP Game Kit
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current version based on date
        id: version
        run: echo "version=$(date +'%Y_%m_%d')" >> $GITHUB_OUTPUT
      - name: Build Win32 release
        run: ./build_gamekit_windows.sh "${{ steps.version.outputs.version }}"
      - name: Prepare a package for qSpider
        run: ./build_games_package.sh qspider
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ steps.version.outputs.version }}
          body: ${{ inputs.annotation }}
          files: dist/*
