on:
  workflow_dispatch:
    inputs:
      annotation:
        description: 'Comments'

name: Release latest QSP Game Kit
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current version based on date
        id: version
        run: echo "::set-output version=date::$(date +'%Y_%m_%d')"
      - name: Build release
        run: ./build_gamekit.sh "${{ steps.version.outputs.version }}"
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          body: ${{ inputs.annotation }}
          files: dist/*
